"""Add detailed fields to Product table

Revision ID: 28ba163ca24e
Revises: 
Create Date: 2025-09-12 18:00:17.861800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28ba163ca24e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('category', sa.String(), nullable=True))
    op.add_column('products', sa.Column('supplier', sa.String(), nullable=True))
    op.add_column('products', sa.Column('reorder_level', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('cost_price', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('selling_price', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('last_restocked', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_column('products', 'last_restocked')
    op.drop_column('products', 'selling_price')
    op.drop_column('products', 'cost_price')
    op.drop_column('products', 'reorder_level')
    op.drop_column('products', 'supplier')
    op.drop_column('products', 'category')
    op.drop_column('products', 'description')
    # ### end Alembic commands ###
